# Generated by Django 6.0.2 on 2026-02-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Sound', 'Sound'), ('Lighting', 'Lighting'), ('Video', 'Video'), ('Power', 'Power'), ('Truss & Rigging', 'Truss & Rigging'), ('Accessories', 'Accessories')], default='Sound', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_maintained',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
