# Generated by Django 6.0.2 on 2026-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_asset_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Sound System', 'Sound System'), ('AV Equipment', 'AV Equipment'), ('IT & Networking', 'IT & Networking'), ('LED Wall', 'LED Wall'), ('Other', 'Other'), ('Lighting', 'Lighting'), ('Power', 'Power'), ('Truss & Rigging', 'Truss & Rigging')], default='Sound', max_length=50),
        ),
    ]
