# Generated by Django 6.0.2 on 2026-02-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='transport_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
