# Generated by Django 6.0.2 on 2026-02-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conference_gst_number_conference_transport_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AM AUDIOVISUALS PVT LTD', max_length=200)),
                ('address', models.TextField(default='Warehouse Complex 7, Industrial Area Phase II, New Delhi - 110020.')),
                ('phone', models.CharField(default='+91 9999 888 777', max_length=50)),
                ('email', models.EmailField(default='support@amaudiovisuals.in', max_length=254)),
                ('gst_number', models.CharField(default='07AAMAU9988Z2Z1', max_length=50)),
                ('website', models.CharField(blank=True, default='www.amaudiovisuals.in', max_length=100)),
            ],
        ),
    ]
