# Generated by Django 6.0.2 on 2026-02-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
