# Generated by Django 6.0.2 on 2026-03-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_asset_category_remove_asset_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_assets', to='core.asset'),
        ),
    ]
