# Generated by Django 6.0.2 on 2026-03-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asset_parent_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='barcode_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='qr_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
