# Generated by Django 6.0.2 on 2026-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_asset_barcode_type_asset_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='crosscheck_assets',
            field=models.ManyToManyField(blank=True, related_name='crosscheck_conferences', to='core.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Damaged', 'Damaged'), ('Crosscheck', 'Crosscheck')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='conference',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='assigned_conferences', to='core.asset'),
        ),
    ]
