# Generated by Django 6.0.2 on 2026-03-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_conference_crosscheck_assets_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='powered_by_name',
            field=models.CharField(default='am audiovisuals', max_length=200),
        ),
    ]
