# Generated by Django 6.0.2 on 2026-03-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_companysettings_logo_companysettings_powered_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='dashboard_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config for dashboard cards visibility'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='theme_template',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green')], default='blue', max_length=20),
        ),
    ]
