# Generated by Django 4.2.29 on 2026-03-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companysettings_dashboard_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_conferences', to='core.employee'),
        ),
    ]
