# Generated by Django 6.0.3 on 2026-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_conference_assigned_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('Sound System', 'Sound System'), ('AV Equipment', 'AV Equipment'), ('IT & Networking', 'IT & Networking'), ('LED Wall', 'LED Wall'), ('Lighting', 'Lighting'), ('Power', 'Power'), ('Truss & Rigging', 'Truss & Rigging'), ('Consumables', 'Consumables'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
