# Generated by Django 6.0.3 on 2026-03-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_asset_quantity_alter_asset_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
