# Generated by Django 6.0.2 on 2026-03-17 10:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_asset_serial_number_alter_asset_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='depreciation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
