# Generated by Django 6.0.3 on 2026-03-17 11:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fix_decimal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='depreciation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
    ]
