# Generated by Django 4.2.29 on 2026-03-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='eway_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='eway_bill_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='conference',
            name='eway_bill_pdf',
            field=models.FileField(blank=True, null=True, upload_to='eway_bills/'),
        ),
        migrations.AddField(
            model_name='conference',
            name='transporter_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='conference',
            name='transporter_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
