# Generated by Django 4.2.29 on 2026-03-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_conference_eway_bill_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='eway_bill_date',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='eway_bill_number',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='eway_bill_pdf',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='transporter_id',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='transporter_name',
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('Speakers & Audio', 'Speakers & Audio'), ('Audio Mixers', 'Audio Mixers'), ('Microphones', 'Microphones'), ('Laptops', 'Laptops'), ('Smartphones', 'Smartphones'), ('Computers & Servers', 'Computers & Servers'), ('IT & Networking', 'IT & Networking'), ('Peripherals', 'Peripherals'), ('Monitors', 'Monitors'), ('TVs', 'TVs'), ('Projectors', 'Projectors'), ('LED Wall', 'LED Wall'), ('Lighting & LED', 'Lighting & LED'), ('Video Switchers', 'Video Switchers'), ('Capture Cards', 'Capture Cards'), ('Splitters & Converters', 'Splitters & Converters'), ('Cameras', 'Cameras'), ('UPS & Power', 'UPS & Power'), ('Consumables', 'Consumables'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
