# Generated by Django 4.2.29 on 2026-03-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_conference_eway_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, default='technician', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('Speakers & Audio', 'Speakers & Audio'), ('Audio Mixers', 'Audio Mixers'), ('Microphones', 'Microphones'), ('Laptops', 'Laptops'), ('Smartphones', 'Smartphones'), ('Computers & Servers', 'Computers & Servers'), ('IT & Networking', 'IT & Networking'), ('Peripherals', 'Peripherals'), ('Monitors', 'Monitors'), ('TVs', 'TVs'), ('Projectors', 'Projectors'), ('Lighting & LED', 'Lighting & LED'), ('Video Switchers', 'Video Switchers'), ('Capture Cards', 'Capture Cards'), ('Splitters & Converters', 'Splitters & Converters'), ('Cameras', 'Cameras'), ('UPS & Power', 'UPS & Power'), ('Printers', 'Printers'), ('Consumables', 'Consumables'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
