# Generated by Django 6.0.2 on 2026-03-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_employee_role_alter_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='flag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Expired', 'Expired'), ('Required Service', 'Required Service'), ('On Service', 'On Service'), ('Missing', 'Missing')], db_index=True, default='', max_length=20),
        ),
    ]
