# Generated by Django 6.0.2 on 2026-03-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_asset_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='conference_pdfs/'),
        ),
    ]
