# Generated by Django 4.2.29 on 2026-03-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_conference_pdf_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='requirement_conferences', to='core.asset'),
        ),
    ]
