# Generated by Django 4.2.29 on 2026-04-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_conference_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='print_label_height',
            field=models.IntegerField(default=25, help_text='Label height in mm'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='print_label_width',
            field=models.IntegerField(default=50, help_text='Label width in mm'),
        ),
    ]
