# Generated by Django 6.0.2 on 2026-04-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auditlog'),
        ('core', '0027_companysettings_print_label_height_and_more'),
    ]

    operations = [
    ]
