# Generated by Django 4.2.29 on 2026-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auditlog'),
        ('core', '0027_companysettings_print_label_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Damaged', 'Damaged'), ('Crosscheck', 'Crosscheck'), ('On Service', 'On Service'), ('Expired', 'Expired'), ('Missing', 'Missing')], db_index=True, default='Available', max_length=20),
        ),
    ]
