# Generated by Django 6.0.2 on 2026-04-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='approximate_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
