# Generated by Django 6.0.2 on 2026-04-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_conference_approximate_value_delete_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('Speakers & Audio', 'Speakers & Audio'), ('Audio Mixers', 'Audio Mixers'), ('Microphones', 'Microphones'), ('Laptops', 'Laptops'), ('Smartphones', 'Smartphones'), ('Computers & Servers', 'Computers & Servers'), ('IT & Networking', 'IT & Networking'), ('Peripherals', 'Peripherals'), ('Monitors', 'Monitors'), ('TVs', 'TVs'), ('Projectors', 'Projectors'), ('Lighting & LED', 'Lighting & LED'), ('Video Switchers', 'Video Switchers'), ('Capture Cards', 'Capture Cards'), ('Splitters & Converters', 'Splitters & Converters'), ('Cameras', 'Cameras'), ('UPS & Power', 'UPS & Power'), ('Printers', 'Printers'), ('Consumables', 'Consumables'), ('Cable', 'Cable'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
