# Generated by Django 4.2.30 on 2026-04-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_conference_approximate_value_delete_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('driver_phone', models.CharField(blank=True, default='', max_length=20)),
                ('driver_name', models.CharField(blank=True, default='', max_length=100)),
                ('challan_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='shipments', to='core.asset')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.conference')),
            ],
        ),
    ]
