# Generated by Django 4.2.30 on 2026-04-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='challan_assets',
            field=models.ManyToManyField(blank=True, related_name='challan_conferences', to='core.asset'),
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
