# Generated by Django 6.0.2 on 2026-04-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_asset_type'),
        ('core', '0032_conference_challan_assets_delete_shipment'),
    ]

    operations = [
    ]
