# Generated by Django 6.0.2 on 2026-04-23 05:18

from django.db import migrations


def forwards_func(apps, schema_editor):
    Asset = apps.get_model('core', 'Asset')
    Asset.objects.filter(type='Consumables').update(type='Cable')

def reverse_func(apps, schema_editor):
    Asset = apps.get_model('core', 'Asset')
    Asset.objects.filter(type='Cable').update(type='Consumables')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20260423_1048'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
