# Generated by Django 4.2.30 on 2026-04-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_subrentalcompany_asset_subrental_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
