# Generated by Django 4.2.30 on 2026-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_asset_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='flag_log',
            field=models.JSONField(blank=True, default=list, help_text="Log of assets flagged during this conference: [{'asset_id': 1, 'flag': 'Missing', 'stage': 'Packup', 'timestamp': '...'}]"),
        ),
    ]
