# Generated by Django 4.2.30 on 2026-04-23 08:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_conference_flag_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubrentalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_till', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.subrentalcompany')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrental_tickets', to='core.conference')),
            ],
        ),
        migrations.CreateModel(
            name='SubrentalTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='core.asset')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.subrentalticket')),
            ],
        ),
    ]
