# Generated by Django 4.2.30 on 2026-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_subrentalticket_subrentalticketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
