# Generated by Django 6.0.2 on 2026-04-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_asset_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='challan_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='conference',
            name='staged_assets',
            field=models.ManyToManyField(blank=True, related_name='staged_conferences', to='core.asset'),
        ),
    ]
