# Generated by Django 4.2.30 on 2026-06-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_conference_challan_number_conference_staged_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='is_audit',
            field=models.BooleanField(default=False, help_text='If True, this conference is a non-blocking audit list. Its assets will not lock availability for other conferences.'),
        ),
    ]
