# Generated by hand on 2026-07-16

from django.db import migrations

def fix_existing_audit_conference_statuses(apps, schema_editor):
    Conference = apps.get_model('core', 'Conference')
    Asset = apps.get_model('core', 'Asset')
    
    # 1. Find all conferences where is_audit is True
    audit_conferences = Conference.objects.filter(is_audit=True)
    
    for conf in audit_conferences:
        # Get all assets in this audit conference
        assets = conf.assets.all()
        if not assets.exists():
            continue
            
        pk_set = set(assets.values_list('pk', flat=True))
        
        # Find which of these assets are also used in OTHER non-audit conferences
        others_using = set(
            Conference.objects
            .exclude(pk=conf.pk)
            .exclude(is_audit=True)
            .filter(assets__in=pk_set)
            .values_list('assets__id', flat=True)
        )
        
        # Find which of these assets are in crosscheck of ANY conference
        crosscheck_using = set(
            Conference.objects
            .filter(crosscheck_assets__in=pk_set)
            .values_list('crosscheck_assets__id', flat=True)
        )
        
        # Assets that are not in use anywhere else (and not in crosscheck) should be Available
        to_revert = [aid for aid in pk_set if aid not in others_using and aid not in crosscheck_using]
        if to_revert:
            # We want to change their status from 'In Use' to 'Available'
            Asset.objects.filter(pk__in=to_revert, status='In Use').update(status='Available')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_j109_add_is_audit_to_conference'),
    ]

    operations = [
        migrations.RunPython(fix_existing_audit_conference_statuses, reverse_code=migrations.RunPython.noop),
    ]
