# Generated by Django 4.2.30 on 2026-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_fix_audit_conference_asset_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='consumable_data',
            field=models.JSONField(blank=True, default=dict, help_text="Tracks consumable quantities per conference: {'asset_id': {'requested': 5, 'returned': 3, 'consumed': 2, 'status': 'settled'}}"),
        ),
    ]
