# Generated by Django 4.2.30 on 2026-08-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_conference_consumable_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='transfer_log',
            field=models.JSONField(blank=True, default=list, help_text="Audit log of all asset transfers: [{'timestamp': '...', 'direction': 'outgoing'|'incoming', 'transferred_asset_ids': [], 'asset_names': [], 'to/from_conference_id': X, 'to/from_conference_name': '...', 'from_address': '...', 'transferred_by': '...'}]"),
        ),
    ]
