# Generated by Django 4.2.30 on 2026-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_conference_transfer_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='next_challan_number',
            field=models.IntegerField(default=1000, help_text='Next auto-generated challan number'),
        ),
    ]
