# Generated by Django 4.2.30 on 2026-08-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_sync_challan_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='challan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
