# Generated by Django 4.2.30 on 2026-08-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_conference_challan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('godown_incharge', 'Godown Incharge'), ('technician', 'Technician'), ('accounts', 'Accounts')], default='technician', max_length=20),
        ),
        migrations.CreateModel(
            name='TruckChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('driver_phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='truck_challans', to='core.asset')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_challans', to='core.conference')),
            ],
            options={
                'ordering': ['truck_number'],
                'unique_together': {('conference', 'truck_number')},
            },
        ),
    ]
