# Generated by Django 4.2.30 on 2026-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_truckchallan_challan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='is_invoiced',
            field=models.BooleanField(default=False, help_text='Track if challan has been marked invoiced by accounts'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='challan_prefix',
            field=models.CharField(blank=True, default='AMDL', help_text="Fixed prefix in challan number (e.g. 'AMDL' → '26-27/AMDL-00122')", max_length=20),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='next_challan_number',
            field=models.IntegerField(default=1, help_text='Next sequential challan number within the current financial year'),
        ),
    ]
