# Generated by Django 4.2.30 on 2026-09-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_conference_is_invoiced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckchallan',
            name='asset_quantities',
            field=models.JSONField(blank=True, default=dict, help_text="Per-asset allocated quantity in this truck: {'<asset_id>': <quantity>}"),
        ),
    ]
