# Generated by Django 4.2.30 on 2026-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_truckchallan_asset_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('boss', 'Boss / Executive'), ('godown_incharge', 'Godown Incharge'), ('technician', 'Technician'), ('accounts', 'Accounts')], default='technician', max_length=20),
        ),
    ]
